# Site settings
title:          KiwakoKaneda
description:    "KiwakoKaneda"
baseurl:        "kiwakokaneda.github.io"
url:            "http://kiwakokaneda.net"

# Author
author:
  name:         KiwakoKaneda
  url:          http://kiwakokaneda.net
  email:        kiwakokaneda@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
